pipeline {
    agent {
        label "jenkins-agent"
    }
    environment {
        APP_NAME = "complete-prodcution-e2e-pipeline"
    }

    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }
    
    
        stage("Checkout from SCM") {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/omarbarkallah/gitops-complete-prodcution-e2e-pipeline.git'
            }
        }
    

    
        stage("Update the Deployment Tags") {
            steps {
                script{
                    def yamlFilePath = "webapp/deployment.yaml"  // Update this with the actual path
                    def updatedYaml = readFile(yamlFilePath).replaceAll(/image: omarbarkallah\/complete-production-e2e-pipeline:.*/, "image: omarbarkallah/complete-production-e2e-pipeline:${params.IMAGE_TAG}")
                    writeFile(file: yamlFilePath, text: updatedYaml)
                }
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                sh """
                    git config --global user.name "omar"
                    git config --global user.email "barkallah.omar8@gmail.com"
                    git add $yamlFilePath
                    git commit -m "Updated Deployment Manifest"
                """
                withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                    sh "git push https://github.com/omarbarkallah/gitops-complete-prodcution-e2e-pipeline.git main"
                }
            }
        }

    }

}